= VPRO STRAPI poc
:toc:
:toclevels: 4

[source, bash]
----
npx create-strapi-app@latest strapi-poc
Need to install the following packages:
  create-strapi-app@4.11.3
Ok to proceed? (y) y
? Choose your installation type Custom (manual settings)
? Choose your preferred language TypeScript
? Choose your default database client postgres
? Database name: strapi-poc
? Host: 127.0.0.1
? Port: 5432
? Username: strapi
? Password: ******
? Enable SSL connection: No

Creating a project with custom database options.
Creating a new Strapi application at /Users/michiel/github/vpro/strapi-poc/strapi-poc.
Creating files.
Dependencies installed successfully.

Your application was created at /Users/michiel/github/vpro/strapi-poc/strapi-poc.

Available commands in your project:

  yarn develop
  Start Strapi in watch mode. (Changes in Strapi project files will trigger a server restart)

  yarn start
  Start Strapi without watch mode.

  yarn build
  Build Strapi admin panel.

  yarn strapi
  Display all available commands.

You can start by doing:

  cd /Users/michiel/github/vpro/strapi-poc/strapi-poc
  yarn develop



----

[source, psql]
----
michiel@mitulo:(poms)~$ psq
psql (14.8 (Homebrew))
Type "help" for help.

postgres=# create database "strapi-poc"
CREATE DATABASE
postgres=# create user "strapi" password 'strapi';
CREATE ROLE
postgres=# grant all privileges on database "strapi-poc" to strapi;
GRANT
----

==

Token: 266de64888be1fc4a7b70846e83456e37244e895ce3970fba286288b05419bb7ff1d3ceb729f13237fe77507ca1de9f0547c5316b7c0dceab39344c6a7da2d2d3dbcca412dff6332f74d999d554dfd0000832957a70f4f181c34280a03c12c5bec4d8fcf21a01bfa402dc59e89c911986260fafcf244a312fa5ee72168a27c51


Forget password:

[source, bash]]
----
 yarn strapi admin:reset-user-password --email="michiel.meeuwissen@gmail.com" --password="Admin2000k"
yarn run v1.22.19
----

== Migration

I performed a test migration link:./migrate-test/3voor12-updates.py[here]


== Remarks

=== ids
Ids are integers. So could not use uuid. So needed to store the original id in a separate field.

=== workflow

Any object can just be draft or published. This seems to be arranged with the implicit 'published_at' field, which is `null` for drafts.
I don't find anything fancier than that.


=== development

yarn is pushed. If using yarn develop then the server is restarted implicitily very often.

==== schema in code

Seems nice


=== Authorization

Similar to other systems (prepr, directus)

There are 3 roles. Author: may create and edit their own object.Editor: may edit all objects. Admin: may do everything.

You can create new roles, which can have permissions per table 'content type'.

=== API's

There is a straighforward REST API: https://docs.strapi.io/dev-docs/api/rest

There is a graphql API: https://docs.strapi.io/dev-docs/api/graphql as a plugin.

=== Plugins

[source, bash]
----
yarn strapi install graphql

----

let's see what happens


=== Custom field types

https://docs.strapi.io/dev-docs/custom-fields

I haven't done this yet, but there are plugin which do stuff like 'country select' and 'encryptable field', which probably proofs that most things we might want are possible without support.

=== Richtext

Rich text is stored as markdown. So during conversion we need to convert the html to markdown.

I actually think this may be preferabble over html. Though I might have preferred asciidoc, which is better defined.

There are plugins for ckeditor


== Bugs

- I started with a collection type '3voor12update', which just gives errors. Drievoor12update works.
- http://localhost:1337/admin/list-plugins is something giving empty responses

== Conclusions?

- STRAPI too seems to be a straight forward headless cms.
- Backend by a relational database
- Can be self-hosted easily
- Develop in development mode, which may change local files, which can be simply committed then.
- ids are ids.
- I don't know whether the api can be deployed seperately from the admin interface. Probably.
- There are plugins availble for all kind of things.
